#!/usr/bin/env bash
# shellcheck disable=all
#ddev-generated
## Description: Run redis-cli inside the redis container
## Usage: redis-cli [flags] [args]
## Example: "redis-cli KEYS *" or "ddev redis-cli INFO" or "ddev redis-cli --version"

if [ -f /etc/redis/conf/security.conf ]; then
  redis-cli -p 6379 -h redis -a redis --no-auth-warning "$@"
else
  redis-cli -p 6379 -h redis "$@"
fi
